services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    init: true
    ports:
      - "5050:5000"

    # Exposed by Dockerfile
    # env_file: ./.env  # Uncomment if .env file exists
    # No external dependencies detected from project files
    # No volumes needed as this is not a database or persistent service
